version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis:/var/lib/redis/data
      - .redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"