version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    env_file:
      - app.env
    networks:
      - app-network
  app:
    container_name: rate-limiter
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge